server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
    max-http-header-size: 102400

  # 项目访问路径
  servlet:
    context-path: /oa



spring:
  profiles:
    active: dev
  multipart:
    max-file-size: 10MB
    max-request-size: 100MB
  # 处理404 异常，关闭资源映射，不让Mvc 自己跳转到 error 请求，直接抛出NoHandlerFoundException 异常，在全局异常捕获
#  mvc:
#    throw-exception-if-no-handler-found: false
#  resources:
#    add-mappings: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  typeAliasesPackage: cn.yj.user.entity.po,cn.yj.core
  global-config:
    db-config:
      #  logic-delete-value: 1       # 逻辑已删除值(默认为 1)
      #  logic-not-delete-value: 0   # 逻辑未删除值(默认为 0)
      table-prefix: tb_   # 统一表前缀名

    db-type: mysql
    # Mapper 对应的 XML 文件，默认不自动刷新
    #如果配置了该属性，Mapper 对应的 XML 文件会自动刷新，更改 XML 文件后，无需再次重启工程
    refresh: true

pagehelper:
  helper-dialect: mysql
  mapper-package: cn.yj
  reasonable: false # true:当默认值为pageNum<=0时，自动配置为1，pageSize>pages时候，默认为最后一页
  supportMethodsArguments: false # 不支持参数接口分页







